 Network avelfir-java_default  Creating
 Network avelfir-java_default  Created
 Container db  Creating
 Container db  Created
 Container avelfir-java-api02-1  Creating
 Container avelfir-java-api01-1  Creating
 Container avelfir-java-api02-1  Created
 Container avelfir-java-api01-1  Created
 Container loadbalancer  Creating
 Container loadbalancer  Created
Attaching to api01-1, api02-1, db, loadbalancer
db            | The files belonging to this database system will be owned by user "postgres".
db            | This user must also own the server process.
db            | 
db            | The database cluster will be initialized with locale "en_US.utf8".
db            | The default database encoding has accordingly been set to "UTF8".
db            | The default text search configuration will be set to "english".
db            | 
db            | Data page checksums are disabled.
db            | 
db            | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db            | creating subdirectories ... ok
db            | selecting dynamic shared memory implementation ... posix
db            | selecting default max_connections ... 100
db            | selecting default shared_buffers ... 128MB
db            | selecting default time zone ... Etc/UTC
db            | creating configuration files ... ok
db            | running bootstrap script ... ok
db            | performing post-bootstrap initialization ... ok
db            | initdb: warning: enabling "trust" authentication for local connections
db            | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db            | syncing data to disk ... ok
db            | 
db            | 
db            | Success. You can now start the database server using:
db            | 
db            |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db            | 
loadbalancer  | 2024/03/10 16:15:48 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.176.4:20000/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:15:48 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/1/extrato", host: "localhost:9999"
db            | waiting for server to start....2024-03-10 16:15:48.639 UTC [48] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db            | 2024-03-10 16:15:48.643 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db            | 2024-03-10 16:15:48.715 UTC [51] LOG:  database system was shut down at 2024-03-10 16:15:48 UTC
db            | 2024-03-10 16:15:48.724 UTC [48] LOG:  database system is ready to accept connections
db            |  done
db            | server started
db            | CREATE DATABASE
db            | 
db            | 
db            | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db            | CREATE TABLE
db            | CREATE TABLE
db            | DO
db            | 
db            | 
db            | 2024-03-10 16:15:49.645 UTC [48] LOG:  received fast shutdown request
db            | waiting for server to shut down....2024-03-10 16:15:49.649 UTC [48] LOG:  aborting any active transactions
db            | 2024-03-10 16:15:49.654 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db            | 2024-03-10 16:15:49.714 UTC [49] LOG:  shutting down
db            | 2024-03-10 16:15:49.721 UTC [49] LOG:  checkpoint starting: shutdown immediate
api02-1       | 
api02-1       |   .   ____          _            __ _ _
api02-1       |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api02-1       | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api02-1       |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api02-1       |   '  |____| .__|_| |_|_| |_\__, | / / / /
api02-1       |  =========|_|==============|___/=/_/_/_/
api02-1       |  :: Spring Boot ::                (v3.2.3)
api02-1       | 
api01-1       | 
api01-1       |   .   ____          _            __ _ _
api01-1       |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api01-1       | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api01-1       |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api01-1       |   '  |____| .__|_| |_|_| |_\__, | / / / /
api01-1       |  =========|_|==============|___/=/_/_/_/
api01-1       |  :: Spring Boot ::                (v3.2.3)
api01-1       | 
db            | 2024-03-10 16:15:50.383 UTC [49] LOG:  checkpoint complete: wrote 933 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.410 s, sync=0.238 s, total=0.669 s; sync files=257, longest=0.209 s, average=0.001 s; distance=4253 kB, estimate=4253 kB
db            | 2024-03-10 16:15:50.387 UTC [48] LOG:  database system is shut down
db            |  done
db            | server stopped
db            | 
db            | PostgreSQL init process complete; ready for start up.
db            | 
db            | 2024-03-10 16:15:50.469 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db            | 2024-03-10 16:15:50.469 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db            | 2024-03-10 16:15:50.469 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db            | 2024-03-10 16:15:50.474 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db            | 2024-03-10 16:15:50.481 UTC [66] LOG:  database system was shut down at 2024-03-10 16:15:50 UTC
db            | 2024-03-10 16:15:50.517 UTC [1] LOG:  database system is ready to accept connections
loadbalancer  | 2024/03/10 16:15:50 [error] 7#7: *4 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:15:52 [error] 7#7: *5 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:15:54 [error] 7#7: *6 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
db            | 2024-03-10 16:15:55.019 UTC [76] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:15:56 [error] 7#7: *7 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:15:58 [error] 7#7: *8 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:16:00 [error] 7#7: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:16:00 [error] 7#7: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.176.4:20000/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:16:02 [error] 7#7: *12 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:16:04 [error] 7#7: *13 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
db            | 2024-03-10 16:16:05.220 UTC [91] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:16:06 [error] 7#7: *14 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:16:08 [error] 7#7: *15 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:16:10 [error] 7#7: *16 no live upstreams while connecting to upstream, client: 192.168.176.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
db            | 2024-03-10 16:16:15.419 UTC [100] FATAL:  role "root" does not exist
db            | 2024-03-10 16:16:25.623 UTC [107] FATAL:  role "root" does not exist
db            | 2024-03-10 16:16:35.822 UTC [115] FATAL:  role "root" does not exist
db            | 2024-03-10 16:16:46.021 UTC [122] FATAL:  role "root" does not exist
db            | 2024-03-10 16:16:56.228 UTC [131] FATAL:  role "root" does not exist
db            | 2024-03-10 16:17:06.426 UTC [138] FATAL:  role "root" does not exist
db            | 2024-03-10 16:17:16.716 UTC [146] FATAL:  role "root" does not exist
db            | 2024-03-10 16:17:27.016 UTC [153] FATAL:  role "root" does not exist
db            | 2024-03-10 16:17:37.321 UTC [160] FATAL:  role "root" does not exist
db            | 2024-03-10 16:17:47.624 UTC [167] FATAL:  role "root" does not exist
db            | 2024-03-10 16:17:57.824 UTC [175] FATAL:  role "root" does not exist
db            | 2024-03-10 16:18:08.217 UTC [183] FATAL:  role "root" does not exist
db            | 2024-03-10 16:18:18.528 UTC [191] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43377 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/5/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43381 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/5/transacoes", host: "localhost:9999"
api02-1       | Killed
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43385 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/3/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43389 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/3/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43393 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/3/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43397 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/2/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43401 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/2/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43405 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/4/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43409 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/1/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43413 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/3/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43417 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "GET /clientes/2/extrato HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/2/extrato", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43419 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/2/transacoes", host: "localhost:9999"
loadbalancer  | 2024/03/10 16:18:27 [error] 7#7: *43425 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.176.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/3/transacoes", host: "localhost:9999"
db            | 2024-03-10 16:18:28.926 UTC [198] FATAL:  role "root" does not exist
api02-1 exited with code 0
api02-1       | 
api02-1       |   .   ____          _            __ _ _
api02-1       |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api02-1       | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api02-1       |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api02-1       |   '  |____| .__|_| |_|_| |_\__, | / / / /
api02-1       |  =========|_|==============|___/=/_/_/_/
api02-1       |  :: Spring Boot ::                (v3.2.3)
api02-1       | 
loadbalancer  | 2024/03/10 16:18:38 [error] 7#7: *50546 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.176.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/4/transacoes", host: "localhost:9999"
db            | 2024-03-10 16:18:39.319 UTC [206] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:18:49 [error] 7#7: *58031 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.176.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.176.3:20000/clientes/4/transacoes", host: "localhost:9999"
db            | 2024-03-10 16:18:49.716 UTC [217] FATAL:  role "root" does not exist
db            | 2024-03-10 16:19:00.125 UTC [225] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:19:06 [alert] 1#1: worker process 7 exited on signal 9
db            | 2024-03-10 16:19:10.517 UTC [231] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:19:11 [alert] 1#1: worker process 8 exited on signal 9
loadbalancer  | 2024/03/10 16:19:15 [alert] 1#1: worker process 9 exited on signal 9
db            | 2024-03-10 16:19:20.916 UTC [239] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:19:21 [alert] 1#1: worker process 10 exited on signal 9
loadbalancer  | 2024/03/10 16:19:24 [alert] 1#1: worker process 11 exited on signal 9
loadbalancer  | 2024/03/10 16:19:27 [alert] 1#1: worker process 12 exited on signal 9
db            | 2024-03-10 16:19:31.527 UTC [247] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:19:38 [alert] 1#1: worker process 13 exited on signal 9
db            | 2024-03-10 16:19:41.919 UTC [254] FATAL:  role "root" does not exist
loadbalancer  | 2024/03/10 16:19:47 [alert] 1#1: worker process 14 exited on signal 9
db            | 2024-03-10 16:19:52.317 UTC [263] FATAL:  role "root" does not exist
db            | 2024-03-10 16:20:02.625 UTC [270] FATAL:  role "root" does not exist
db            | 2024-03-10 16:20:13.016 UTC [278] FATAL:  role "root" does not exist
db            | 2024-03-10 16:20:23.524 UTC [285] FATAL:  role "root" does not exist
loadbalancer exited with code 0
loadbalancer exited with code 0
db            | 2024-03-10 16:20:33.632 UTC [293] FATAL:  role "root" does not exist
api01-1 exited with code 0
api01-1 exited with code 137
api02-1 exited with code 0
api02-1 exited with code 137
db            | 2024-03-10 16:20:38.017 UTC [1] LOG:  received fast shutdown request
db            | 2024-03-10 16:20:38.020 UTC [1] LOG:  aborting any active transactions
db            | 2024-03-10 16:20:38.021 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db            | 2024-03-10 16:20:38.021 UTC [64] LOG:  shutting down
db            | 2024-03-10 16:20:38.024 UTC [64] LOG:  checkpoint starting: shutdown immediate
db            | 2024-03-10 16:20:38.167 UTC [64] LOG:  checkpoint complete: wrote 585 buffers (3.6%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.014 s, sync=0.106 s, total=0.146 s; sync files=30, longest=0.097 s, average=0.004 s; distance=15736 kB, estimate=15736 kB
db            | 2024-03-10 16:20:38.171 UTC [1] LOG:  database system is shut down
db exited with code 0
