 Network pankkivahva-nginx  Creating
 Network pankkivahva-nginx  Created
 Container skvggor-pankkivahva-rust-db-1  Creating
 Container skvggor-pankkivahva-rust-db-1  Created
 Container skvggor-pankkivahva-rust-api01-1  Creating
 Container skvggor-pankkivahva-rust-api02-1  Creating
 Container skvggor-pankkivahva-rust-api01-1  Created
 Container skvggor-pankkivahva-rust-api02-1  Created
 Container skvggor-pankkivahva-rust-load-balancer-1  Creating
 Container skvggor-pankkivahva-rust-load-balancer-1  Created
Attaching to api01-1, api02-1, db-1, load-balancer-1
db-1             | The files belonging to this database system will be owned by user "postgres".
db-1             | This user must also own the server process.
db-1             | 
db-1             | The database cluster will be initialized with locale "en_US.utf8".
db-1             | The default database encoding has accordingly been set to "UTF8".
db-1             | The default text search configuration will be set to "english".
db-1             | 
db-1             | Data page checksums are disabled.
db-1             | 
db-1             | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1             | creating subdirectories ... ok
db-1             | selecting dynamic shared memory implementation ... posix
db-1             | selecting default max_connections ... 100
db-1             | selecting default shared_buffers ... 128MB
db-1             | selecting default time zone ... Etc/UTC
db-1             | creating configuration files ... ok
db-1             | running bootstrap script ... ok
load-balancer-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
load-balancer-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
load-balancer-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
load-balancer-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
load-balancer-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
load-balancer-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
load-balancer-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
load-balancer-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
load-balancer-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1             | performing post-bootstrap initialization ... ok
db-1             | initdb: warning: enabling "trust" authentication for local connections
db-1             | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1             | syncing data to disk ... ok
db-1             | 
db-1             | 
db-1             | Success. You can now start the database server using:
db-1             | 
db-1             |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1             | 
db-1             | waiting for server to start....2024-03-09 19:56:57.717 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1             | 2024-03-09 19:56:57.721 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1             | 2024-03-09 19:56:57.732 UTC [52] LOG:  database system was shut down at 2024-03-09 19:56:57 UTC
db-1             | 2024-03-09 19:56:57.739 UTC [49] LOG:  database system is ready to accept connections
db-1             |  done
db-1             | server started
db-1             | CREATE DATABASE
db-1             | 
db-1             | 
db-1             | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/0001_create_tables.sql
db-1             | CREATE TABLE
db-1             | CREATE TABLE
db-1             | DO
db-1             | 
db-1             | 
db-1             | waiting for server to shut down....2024-03-09 19:56:57.982 UTC [49] LOG:  received fast shutdown request
db-1             | 2024-03-09 19:56:57.986 UTC [49] LOG:  aborting any active transactions
db-1             | 2024-03-09 19:56:58.014 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
db-1             | 2024-03-09 19:56:58.014 UTC [50] LOG:  shutting down
db-1             | 2024-03-09 19:56:58.023 UTC [50] LOG:  checkpoint starting: shutdown immediate
db-1             | 2024-03-09 19:56:58.539 UTC [50] LOG:  checkpoint complete: wrote 939 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.397 s, sync=0.093 s, total=0.525 s; sync files=313, longest=0.051 s, average=0.001 s; distance=4290 kB, estimate=4290 kB; lsn=0/191B348, redo lsn=0/191B348
db-1             | 2024-03-09 19:56:58.544 UTC [49] LOG:  database system is shut down
db-1             |  done
db-1             | server stopped
db-1             | 
db-1             | PostgreSQL init process complete; ready for start up.
db-1             | 
db-1             | 2024-03-09 19:56:58.607 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1             | 2024-03-09 19:56:58.607 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1             | 2024-03-09 19:56:58.607 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1             | 2024-03-09 19:56:58.614 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1             | 2024-03-09 19:56:58.622 UTC [67] LOG:  database system was shut down at 2024-03-09 19:56:58 UTC
db-1             | 2024-03-09 19:56:58.629 UTC [1] LOG:  database system is ready to accept connections
load-balancer-1  | 2024/03/09 19:57:00 [error] 29#29: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/1/extrato", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:57:11 [error] 29#29: *216 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/1/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:57:22 [error] 29#29: *701 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/4/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:57:33 [error] 29#29: *1864 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/1/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:57:44 [error] 29#29: *3705 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/5/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:57:55 [error] 29#29: *6226 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/2/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:58:06 [error] 29#29: *9431 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/4/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:58:17 [error] 29#29: *13310 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/1/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:58:28 [error] 29#29: *17871 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/5/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:58:39 [error] 29#29: *23112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/5/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:58:50 [error] 29#29: *29031 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/3/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:59:01 [error] 29#29: *35630 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/2/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:59:12 [error] 29#29: *42899 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/5/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:59:23 [error] 29#29: *50380 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/2/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:59:34 [error] 29#29: *57859 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/1/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:59:45 [error] 29#29: *65338 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/5/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 19:59:56 [error] 29#29: *72823 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/1/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 20:00:07 [error] 29#29: *80302 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/3/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 20:00:18 [error] 29#29: *87785 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/3/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 20:00:29 [error] 29#29: *95266 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/2/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 20:00:40 [error] 29#29: *102747 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/5/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 20:00:51 [error] 29#29: *110228 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/5/transacoes", host: "localhost:9999"
load-balancer-1  | 2024/03/09 20:01:02 [error] 29#29: *117709 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.29.0.3:3001/clientes/1/transacoes", host: "localhost:9999"
load-balancer-1 exited with code 0
load-balancer-1 exited with code 0
api02-1 exited with code 0
api02-1 exited with code 137
api01-1 exited with code 0
api01-1 exited with code 137
db-1             | 2024-03-09 20:01:24.178 UTC [1] LOG:  received fast shutdown request
db-1             | 2024-03-09 20:01:24.182 UTC [1] LOG:  aborting any active transactions
db-1             | 2024-03-09 20:01:24.184 UTC [1] LOG:  background worker "logical replication launcher" (PID 70) exited with exit code 1
db-1             | 2024-03-09 20:01:24.184 UTC [65] LOG:  shutting down
db-1             | 2024-03-09 20:01:24.188 UTC [65] LOG:  checkpoint starting: shutdown immediate
db-1             | 2024-03-09 20:01:24.309 UTC [65] LOG:  checkpoint complete: wrote 613 buffers (3.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.093 s, total=0.126 s; sync files=30, longest=0.087 s, average=0.004 s; distance=2712 kB, estimate=2712 kB; lsn=0/1BC1558, redo lsn=0/1BC1558
db-1             | 2024-03-09 20:01:24.313 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
