 Network gabrielsantoslima_api  Creating
 Network gabrielsantoslima_api  Created
 Container gabrielsantoslima-db-1  Creating
 Container gabrielsantoslima-db-1  Created
 Container gabrielsantoslima-api01-1  Creating
 Container gabrielsantoslima-api02-1  Creating
 Container gabrielsantoslima-api02-1  Created
 Container gabrielsantoslima-api01-1  Created
 Container gabrielsantoslima-nginx-1  Creating
 Container gabrielsantoslima-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api02-1  | 
api02-1  | > fast.money@1.0.0 start
api02-1  | > node build/src/index.js
api02-1  | 
api01-1  | 
api01-1  | > fast.money@1.0.0 start
api01-1  | > node build/src/index.js
api01-1  | 
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
nginx-1  | 2024/03/04 17:56:27 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:27 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-03-04 17:56:28.131 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-04 17:56:28.134 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-04 17:56:28.218 UTC [51] LOG:  database system was shut down at 2024-03-04 17:56:27 UTC
db-1     | 2024-03-04 17:56:28.225 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
db-1     | ALTER SYSTEM
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | INSERT 0 5
db-1     | 
db-1     | 
db-1     | waiting for server to shut down....2024-03-04 17:56:29.215 UTC [48] LOG:  received fast shutdown request
db-1     | 2024-03-04 17:56:29.217 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-03-04 17:56:29.314 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-03-04 17:56:29.315 UTC [49] LOG:  shutting down
db-1     | 2024-03-04 17:56:29.318 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-04 17:56:29.795 UTC [49] LOG:  checkpoint complete: wrote 937 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.373 s, sync=0.092 s, total=0.480 s; sync files=306, longest=0.059 s, average=0.001 s; distance=4284 kB, estimate=4284 kB; lsn=0/1919DE8, redo lsn=0/1919DE8
db-1     | 2024-03-04 17:56:29.800 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-03-04 17:56:29.838 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
nginx-1  | 2024/03/04 17:56:29 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
db-1     | 2024-03-04 17:56:29.914 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-03-04 17:56:29.914 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-03-04 17:56:29.920 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-04 17:56:29.927 UTC [66] LOG:  database system was shut down at 2024-03-04 17:56:29 UTC
db-1     | 2024-03-04 17:56:29.934 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/03/04 17:56:31 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:33 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:35 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:37 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:39 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:39 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:41 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:43 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:45 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:47 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:49 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:51 [error] 29#29: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:51 [error] 29#29: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:53 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:55 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:57 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:56:59 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:57:01 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:57:03 [error] 29#29: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:57:03 [error] 29#29: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.48.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/04 17:57:05 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 192.168.48.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1 exited with code 0
api02-1 exited with code 137
api01-1 exited with code 0
api01-1 exited with code 137
db-1     | 2024-03-04 17:57:19.433 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-03-04 17:57:19.446 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-03-04 17:57:19.448 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-03-04 17:57:19.449 UTC [64] LOG:  shutting down
db-1     | 2024-03-04 17:57:19.453 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-04 17:57:19.520 UTC [64] LOG:  checkpoint complete: wrote 32 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.044 s, total=0.072 s; sync files=13, longest=0.038 s, average=0.004 s; distance=132 kB, estimate=132 kB; lsn=0/193AF98, redo lsn=0/193AF98
db-1     | 2024-03-04 17:57:19.524 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
