 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container ydotnet-db-1  Creating
 Container ydotnet-db-1  Created
 Container ydotnet-api02-1  Creating
 Container ydotnet-api01-1  Creating
 Container ydotnet-api01-1  Created
 Container ydotnet-api02-1  Created
 Container ydotnet-nginx-1  Creating
 Container ydotnet-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-03-02 04:20:24.504 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-02 04:20:24.512 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-02 04:20:24.527 UTC [52] LOG:  database system was shut down at 2024-03-02 04:20:23 UTC
db-1     | 2024-03-02 04:20:24.536 UTC [49] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | 
db-1     | 
db-1     | waiting for server to shut down....2024-03-02 04:20:24.769 UTC [49] LOG:  received fast shutdown request
db-1     | 2024-03-02 04:20:24.773 UTC [49] LOG:  aborting any active transactions
db-1     | 2024-03-02 04:20:24.780 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
db-1     | 2024-03-02 04:20:24.781 UTC [50] LOG:  shutting down
db-1     | 2024-03-02 04:20:24.783 UTC [50] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-02 04:20:25.323 UTC [50] LOG:  checkpoint complete: wrote 946 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.421 s, sync=0.109 s, total=0.543 s; sync files=319, longest=0.059 s, average=0.001 s; distance=4311 kB, estimate=4311 kB; lsn=0/19209A8, redo lsn=0/19209A8
db-1     | 2024-03-02 04:20:25.328 UTC [49] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-03-02 04:20:25.393 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-02 04:20:25.394 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-03-02 04:20:25.394 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-03-02 04:20:25.400 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-02 04:20:25.407 UTC [67] LOG:  database system was shut down at 2024-03-02 04:20:25 UTC
db-1     | 2024-03-02 04:20:25.413 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api01-1  | info: Microsoft.Hosting.Lifetime[14]
api01-1  |       Now listening on: http://[::]:8080
api01-1  | info: Microsoft.Hosting.Lifetime[0]
api01-1  |       Application started. Press Ctrl+C to shut down.
api01-1  | info: Microsoft.Hosting.Lifetime[0]
api01-1  |       Hosting environment: Production
api01-1  | info: Microsoft.Hosting.Lifetime[0]
api01-1  |       Content root path: /app
api02-1  | info: Microsoft.Hosting.Lifetime[14]
api02-1  |       Now listening on: http://[::]:8080
api02-1  | info: Microsoft.Hosting.Lifetime[0]
api02-1  |       Application started. Press Ctrl+C to shut down.
api02-1  | info: Microsoft.Hosting.Lifetime[0]
api02-1  |       Hosting environment: Production
api02-1  | info: Microsoft.Hosting.Lifetime[0]
api02-1  |       Content root path: /app
api01-1  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
api01-1  |       Failed to determine the https port for redirect.
nginx-1  | 2024/03/02 04:20:31 [error] 29#29: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/02 04:20:42 [error] 29#29: *217 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:20:53 [error] 29#29: *687 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:21:04 [error] 29#29: *1834 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:21:15 [error] 29#29: *3663 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:21:26 [error] 29#29: *6170 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:21:37 [error] 29#29: *9359 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:21:48 [error] 29#29: *13226 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:21:59 [error] 29#29: *17777 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:22:10 [error] 29#29: *23002 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:22:21 [error] 29#29: *28909 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:22:32 [error] 29#29: *35494 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:22:43 [error] 29#29: *42751 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:22:54 [error] 29#29: *50228 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:23:05 [error] 29#29: *57713 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:23:16 [error] 29#29: *65194 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:23:27 [error] 29#29: *72675 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:23:38 [error] 29#29: *80156 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:23:49 [error] 29#29: *87635 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:24:00 [error] 29#29: *95118 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:24:11 [error] 29#29: *102599 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:24:22 [error] 29#29: *110080 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1  | 2024/03/02 04:24:33 [error] 29#29: *117561 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://192.168.16.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1  | info: Microsoft.Hosting.Lifetime[0]
api02-1  |       Application is shutting down...
api01-1  | info: Microsoft.Hosting.Lifetime[0]
api01-1  |       Application is shutting down...
api02-1 exited with code 0
api02-1 exited with code 0
api01-1 exited with code 0
api01-1 exited with code 0
db-1     | 2024-03-02 04:24:45.172 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-03-02 04:24:45.175 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-03-02 04:24:45.177 UTC [1] LOG:  background worker "logical replication launcher" (PID 70) exited with exit code 1
db-1     | 2024-03-02 04:24:45.177 UTC [65] LOG:  shutting down
db-1     | 2024-03-02 04:24:45.180 UTC [65] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-02 04:24:45.333 UTC [65] LOG:  checkpoint complete: wrote 615 buffers (3.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.014 s, sync=0.121 s, total=0.157 s; sync files=33, longest=0.112 s, average=0.004 s; distance=3805 kB, estimate=3805 kB; lsn=0/1CD7F70, redo lsn=0/1CD7F70
db-1     | 2024-03-02 04:24:45.337 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
