 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container java-cassiogangrel-postgres-1  Creating
 Container java-cassiogangrel-postgres-1  Created
 Container java-cassiogangrel-api01-1  Creating
 Container java-cassiogangrel-api01-1  Created
 Container java-cassiogangrel-api02-1  Creating
 Container java-cassiogangrel-api02-1  Created
 Container java-cassiogangrel-nginx-1  Creating
 Container java-cassiogangrel-nginx-1  Created
Attaching to api01-1, api02-1, nginx-1, postgres-1
postgres-1  | The files belonging to this database system will be owned by user "postgres".
postgres-1  | This user must also own the server process.
postgres-1  | 
postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-1  | The default database encoding has accordingly been set to "UTF8".
postgres-1  | The default text search configuration will be set to "english".
postgres-1  | 
postgres-1  | Data page checksums are disabled.
postgres-1  | 
postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres-1  | creating subdirectories ... ok
postgres-1  | selecting dynamic shared memory implementation ... posix
postgres-1  | selecting default max_connections ... 100
postgres-1  | selecting default shared_buffers ... 128MB
postgres-1  | selecting default time zone ... Etc/UTC
postgres-1  | creating configuration files ... ok
postgres-1  | running bootstrap script ... ok
api01-1     | __  ____  __  _____   ___  __ ____  ______ 
api01-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1     | 2024-02-19 08:32:47,014 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api01-1     | 2024-02-19 08:32:47,016 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 2024-02-19 08:32:47,017 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api01-1     | 2024-02-19 08:32:47,017 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api01-1     | 2024-02-19 08:32:47,017 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api01-1     | 2024-02-19 08:32:47,017 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 2024-02-19 08:32:47,019 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
api01-1     | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
api01-1     | 	at io.quarkus.runtime.Application.start(Application.java:101)
api01-1     | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
api01-1     | 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
api01-1     | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
api01-1     | SQL State  : 08001
api01-1     | Error Code : 0
api01-1     | Message    : Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 
api01-1     | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
api01-1     | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
api01-1     | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
api01-1     | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
api01-1     | 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
api01-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
api01-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
api01-1     | 	... 7 more
api01-1     | Caused by: org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api01-1     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api01-1     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api01-1     | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api01-1     | 	at org.postgresql.Driver.connect(Driver.java:297)
api01-1     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
api01-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
api01-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
api01-1     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
api01-1     | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api01-1     | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api01-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api01-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api01-1     | Caused by: java.net.ConnectException: Connection refused
api01-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api01-1     | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api01-1     | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api01-1     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api01-1     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api01-1     | 	... 15 more
api01-1     | 
postgres-1  | performing post-bootstrap initialization ... ok
api02-1     | __  ____  __  _____   ___  __ ____  ______ 
api02-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api02-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api02-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api02-1     | 2024-02-19 08:32:48,321 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api02-1     | 2024-02-19 08:32:48,322 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 2024-02-19 08:32:48,323 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api02-1     | 2024-02-19 08:32:48,323 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api02-1     | 2024-02-19 08:32:48,323 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api02-1     | 2024-02-19 08:32:48,323 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 2024-02-19 08:32:48,325 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
api02-1     | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
api02-1     | 	at io.quarkus.runtime.Application.start(Application.java:101)
api02-1     | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
api02-1     | 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
api02-1     | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
api02-1     | SQL State  : 08001
api02-1     | Error Code : 0
api02-1     | Message    : Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 
api02-1     | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
api02-1     | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
api02-1     | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
api02-1     | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
api02-1     | 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
api02-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
api02-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
api02-1     | 	... 7 more
api02-1     | Caused by: org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api02-1     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api02-1     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api02-1     | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api02-1     | 	at org.postgresql.Driver.connect(Driver.java:297)
api02-1     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
api02-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
api02-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
api02-1     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
api02-1     | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api02-1     | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api02-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api02-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api02-1     | Caused by: java.net.ConnectException: Connection refused
api02-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api02-1     | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api02-1     | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api02-1     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api02-1     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api02-1     | 	... 15 more
api02-1     | 
api01-1 exited with code 0
nginx-1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
api01-1     | __  ____  __  _____   ___  __ ____  ______ 
api01-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1     | 2024-02-19 08:32:49,919 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api01-1     | 2024-02-19 08:32:49,921 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 2024-02-19 08:32:49,921 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api01-1     | 2024-02-19 08:32:49,921 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api01-1     | 2024-02-19 08:32:49,921 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api01-1     | 2024-02-19 08:32:49,922 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 2024-02-19 08:32:49,923 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
api01-1     | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
api01-1     | 	at io.quarkus.runtime.Application.start(Application.java:101)
api01-1     | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
api01-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
api01-1     | 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
api01-1     | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
api01-1     | SQL State  : 08001
api01-1     | Error Code : 0
api01-1     | Message    : Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 
api01-1     | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
api01-1     | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
api01-1     | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
api01-1     | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
api01-1     | 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
api01-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
api01-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
api01-1     | 	... 7 more
api01-1     | Caused by: org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api01-1     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api01-1     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api01-1     | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api01-1     | 	at org.postgresql.Driver.connect(Driver.java:297)
api01-1     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
api01-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
api01-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
api01-1     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api01-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
api01-1     | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api01-1     | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api01-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api01-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api01-1     | Caused by: java.net.ConnectException: Connection refused
api01-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api01-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api01-1     | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api01-1     | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api01-1     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api01-1     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api01-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api01-1     | 	... 15 more
api01-1     | 
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1     | /docker-entrypoint.sh: Configuration complete; ready for start up
postgres-1  | initdb: warning: enabling "trust" authentication for local connections
postgres-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres-1  | syncing data to disk ... ok
postgres-1  | 
postgres-1  | 
postgres-1  | Success. You can now start the database server using:
postgres-1  | 
postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres-1  | 
postgres-1  | waiting for server to start....2024-02-19 08:32:50.087 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1  | 2024-02-19 08:32:50.090 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-02-19 08:32:50.103 UTC [52] LOG:  database system was shut down at 2024-02-19 08:32:48 UTC
postgres-1  | 2024-02-19 08:32:50.119 UTC [49] LOG:  database system is ready to accept connections
postgres-1  |  done
postgres-1  | server started
api02-1 exited with code 0
api02-1     | __  ____  __  _____   ___  __ ____  ______ 
api02-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api02-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api02-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api02-1     | 2024-02-19 08:32:50,819 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api02-1     | 2024-02-19 08:32:50,820 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 2024-02-19 08:32:50,821 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api02-1     | 2024-02-19 08:32:50,821 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api02-1     | 2024-02-19 08:32:50,822 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api02-1     | 2024-02-19 08:32:50,822 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 2024-02-19 08:32:50,824 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
api02-1     | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
api02-1     | 	at io.quarkus.runtime.Application.start(Application.java:101)
api02-1     | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
api02-1     | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
api02-1     | 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
api02-1     | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
api02-1     | SQL State  : 08001
api02-1     | Error Code : 0
api02-1     | Message    : Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 
api02-1     | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
api02-1     | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
api02-1     | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
api02-1     | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
api02-1     | 	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
api02-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
api02-1     | 	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
api02-1     | 	... 7 more
api02-1     | Caused by: org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
api02-1     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
api02-1     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
api02-1     | 	at org.postgresql.Driver.makeConnection(Driver.java:444)
api02-1     | 	at org.postgresql.Driver.connect(Driver.java:297)
api02-1     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
api02-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
api02-1     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
api02-1     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
api02-1     | 	at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
api02-1     | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api02-1     | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api02-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api02-1     | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api02-1     | Caused by: java.net.ConnectException: Connection refused
api02-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api02-1     | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api02-1     | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api02-1     | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api02-1     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
api02-1     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
api02-1     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
api02-1     | 	... 15 more
api02-1     | 
postgres-1  | CREATE DATABASE
postgres-1  | 
postgres-1  | 
postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres-1  | 
postgres-1  | 2024-02-19 08:32:50.836 UTC [49] LOG:  received fast shutdown request
postgres-1  | waiting for server to shut down....2024-02-19 08:32:50.865 UTC [49] LOG:  aborting any active transactions
postgres-1  | 2024-02-19 08:32:50.867 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgres-1  | 2024-02-19 08:32:50.868 UTC [50] LOG:  shutting down
postgres-1  | 2024-02-19 08:32:50.875 UTC [50] LOG:  checkpoint starting: shutdown immediate
postgres-1  | 2024-02-19 08:32:51.467 UTC [50] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.402 s, sync=0.139 s, total=0.600 s; sync files=301, longest=0.093 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913068, redo lsn=0/1913068
postgres-1  | 2024-02-19 08:32:51.474 UTC [49] LOG:  database system is shut down
postgres-1  |  done
postgres-1  | server stopped
postgres-1  | 
postgres-1  | PostgreSQL init process complete; ready for start up.
postgres-1  | 
nginx-1     | 2024/02/19 08:32:52 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.25.0.5:8080/clientes/1/extrato", host: "localhost:9999"
postgres-1  | 2024-02-19 08:32:52.033 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1  | 2024-02-19 08:32:52.033 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2024-02-19 08:32:52.033 UTC [1] LOG:  listening on IPv6 address "::", port 5432
api01-1 exited with code 0
postgres-1  | 2024-02-19 08:32:52.053 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-02-19 08:32:52.082 UTC [65] LOG:  database system was shut down at 2024-02-19 08:32:51 UTC
postgres-1  | 2024-02-19 08:32:52.094 UTC [1] LOG:  database system is ready to accept connections
nginx-1     | 2024/02/19 08:32:52 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.25.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:32:52 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/1/extrato", host: "localhost:9999"
api02-1 exited with code 0
api01-1 exited with code 0
api01-1     | __  ____  __  _____   ___  __ ____  ______ 
api01-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1     | 2024-02-19 08:32:53,120 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api01-1     | __  ____  __  _____   ___  __ ____  ______ 
api01-1     |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1     |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1     | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1     | 2024-02-19 08:32:53,120 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.22.3 by Redgate
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.FlywayExecutor] (main) Database: jdbc:postgresql://postgres:5432/rinha (PostgreSQL 16.2)
api01-1     | 2024-02-19 08:32:53,131 INFO  [org.fly.cor.FlywayExecutor] (main) Database: jdbc:postgresql://postgres:5432/rinha (PostgreSQL 16.2)
api01-1     | 2024-02-19 08:32:53,132 WARNING [org.fly.cor.int.dat.bas.Database] (main) Flyway upgrade recommended: PostgreSQL 16.2 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api01-1     | 2024-02-19 08:32:53,132 WARNING [org.fly.cor.int.dat.bas.Database] (main) Flyway upgrade recommended: PostgreSQL 16.2 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api01-1     | 2024-02-19 08:32:53,134 INFO  [org.fly.cor.int.com.DbValidate] (main) Successfully validated 1 migration (execution time 00:00.001s)
api01-1     | 2024-02-19 08:32:53,134 INFO  [org.fly.cor.int.com.DbValidate] (main) Successfully validated 1 migration (execution time 00:00.001s)
api01-1     | 2024-02-19 08:32:53,144 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 1
api01-1     | 2024-02-19 08:32:53,144 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 1
api01-1     | 2024-02-19 08:32:53,144 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary.
api01-1     | 2024-02-19 08:32:53,144 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary.
api01-1     | 2024-02-19 08:32:53,146 INFO  [io.quarkus] (main) rinha_e2 1.0.0 native (powered by Quarkus 3.7.2) started in 0.096s. Listening on: http://0.0.0.0:8080
api01-1     | 2024-02-19 08:32:53,146 INFO  [io.quarkus] (main) Profile prod activated. 
api01-1     | 2024-02-19 08:32:53,146 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, vertx]
api01-1     | 2024-02-19 08:32:53,146 INFO  [io.quarkus] (main) rinha_e2 1.0.0 native (powered by Quarkus 3.7.2) started in 0.096s. Listening on: http://0.0.0.0:8080
api01-1     | 2024-02-19 08:32:53,146 INFO  [io.quarkus] (main) Profile prod activated. 
api01-1     | 2024-02-19 08:32:53,146 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, vertx]
nginx-1     | 2024/02/19 08:32:54 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:32:56 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:32:58 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:00 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:02 [error] 29#29: *9 no live upstreams while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:04 [error] 29#29: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/1/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:15 [error] 29#29: *217 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "GET /clientes/3/extrato HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/3/extrato", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:26 [error] 29#29: *628 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:37 [error] 29#29: *1717 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:48 [error] 29#29: *3488 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:33:59 [error] 29#29: *5933 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:34:10 [error] 29#29: *9068 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:34:21 [error] 29#29: *12877 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:34:32 [error] 29#29: *17360 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:34:43 [error] 29#29: *22527 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:34:54 [error] 29#29: *28378 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:35:05 [error] 29#29: *34897 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:35:16 [error] 29#29: *42110 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:35:27 [error] 29#29: *49591 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/3/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:35:38 [error] 29#29: *57072 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:35:49 [error] 29#29: *64551 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:36:00 [error] 29#29: *72034 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:36:11 [error] 29#29: *79513 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/1/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:36:22 [error] 29#29: *86992 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:36:33 [error] 29#29: *94475 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:36:44 [error] 29#29: *101958 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/5/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:36:55 [error] 29#29: *109439 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/4/transacoes", host: "localhost:9999"
nginx-1     | 2024/02/19 08:37:06 [error] 29#29: *116917 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.25.0.4:8081/clientes/2/transacoes", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1     | 2024-02-19 08:37:18,031 INFO  [io.quarkus] (Shutdown thread) rinha_e2 stopped in 0.009s
api02-1 exited with code 0
api02-1 exited with code 143
api01-1     | 2024-02-19 08:37:18,611 INFO  [io.quarkus] (Shutdown thread) rinha_e2 stopped in 0.010s
api01-1     | 2024-02-19 08:37:18,611 INFO  [io.quarkus] (Shutdown thread) rinha_e2 stopped in 0.010s
api01-1 exited with code 0
api01-1 exited with code 143
postgres-1  | 2024-02-19 08:37:19.226 UTC [1] LOG:  received fast shutdown request
postgres-1  | 2024-02-19 08:37:19.230 UTC [1] LOG:  aborting any active transactions
postgres-1  | 2024-02-19 08:37:19.232 UTC [1] LOG:  background worker "logical replication launcher" (PID 68) exited with exit code 1
postgres-1  | 2024-02-19 08:37:19.232 UTC [63] LOG:  shutting down
postgres-1  | 2024-02-19 08:37:19.235 UTC [63] LOG:  checkpoint starting: shutdown immediate
postgres-1  | 2024-02-19 08:37:19.535 UTC [63] LOG:  checkpoint complete: wrote 988 buffers (6.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.179 s, sync=0.105 s, total=0.304 s; sync files=78, longest=0.061 s, average=0.002 s; distance=22832 kB, estimate=22832 kB; lsn=0/2F5F400, redo lsn=0/2F5F400
postgres-1  | 2024-02-19 08:37:19.540 UTC [1] LOG:  database system is shut down
postgres-1 exited with code 0
