 Container rpy-db  Creating
 Container rpy-db  Created
 Container rpy-api2  Creating
 Container rpy-api1  Creating
 Container rpy-api2  Created
 Container rpy-api1  Created
 Container rpy-proxy  Creating
 Container rpy-proxy  Created
Attaching to rpy-api1, rpy-api2, rpy-db, rpy-proxy
rpy-db     | The files belonging to this database system will be owned by user "postgres".
rpy-db     | This user must also own the server process.
rpy-db     | 
rpy-db     | The database cluster will be initialized with locale "en_US.utf8".
rpy-db     | The default database encoding has accordingly been set to "UTF8".
rpy-db     | The default text search configuration will be set to "english".
rpy-db     | 
rpy-db     | Data page checksums are disabled.
rpy-db     | 
rpy-db     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
rpy-db     | creating subdirectories ... ok
rpy-db     | selecting dynamic shared memory implementation ... posix
rpy-db     | selecting default max_connections ... 100
rpy-db     | selecting default shared_buffers ... 128MB
rpy-db     | selecting default time zone ... Etc/UTC
rpy-db     | creating configuration files ... ok
rpy-db     | running bootstrap script ... ok
rpy-db     | performing post-bootstrap initialization ... ok
rpy-db     | initdb: warning: enabling "trust" authentication for local connections
rpy-db     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
rpy-db     | syncing data to disk ... ok
rpy-db     | 
rpy-db     | 
rpy-db     | Success. You can now start the database server using:
rpy-db     | 
rpy-db     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
rpy-db     | 
rpy-db     | waiting for server to start....2024-03-03 03:13:00.244 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rpy-db     | 2024-03-03 03:13:00.244 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rpy-db     | 2024-03-03 03:13:00.245 UTC [52] LOG:  database system was shut down at 2024-03-03 03:13:00 UTC
rpy-db     | 2024-03-03 03:13:00.248 UTC [49] LOG:  database system is ready to accept connections
rpy-db     |  done
rpy-db     | server started
rpy-db     | CREATE DATABASE
rpy-db     | 
rpy-db     | 
rpy-db     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/ddl-postgresql.sql
rpy-db     | SET
rpy-db     | SET
rpy-db     | SET
rpy-db     | SET
rpy-db     | SET
rpy-db     | CREATE TABLE
rpy-db     | CREATE INDEX
rpy-db     | CREATE TABLE
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | INSERT 0 1
rpy-db     | CREATE VIEW
rpy-db     | CREATE SEQUENCE
rpy-db     | CREATE FUNCTION
rpy-db     | 
rpy-db     | 
rpy-db     | waiting for server to shut down...2024-03-03 03:13:00.525 UTC [49] LOG:  received fast shutdown request
rpy-db     | .2024-03-03 03:13:00.525 UTC [49] LOG:  aborting any active transactions
rpy-db     | 2024-03-03 03:13:00.527 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
rpy-db     | 2024-03-03 03:13:00.528 UTC [50] LOG:  shutting down
rpy-db     | 2024-03-03 03:13:00.528 UTC [50] LOG:  checkpoint starting: shutdown immediate
rpy-db     | 2024-03-03 03:13:00.532 UTC [50] LOG:  checkpoint complete: wrote 938 buffers (7.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.001 s, total=0.005 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4293 kB, estimate=4293 kB; lsn=0/191C1E0, redo lsn=0/191C1E0
rpy-db     | 2024-03-03 03:13:00.537 UTC [49] LOG:  database system is shut down
rpy-db     |  done
rpy-db     | server stopped
rpy-db     | 
rpy-db     | PostgreSQL init process complete; ready for start up.
rpy-db     | 
rpy-db     | 2024-03-03 03:13:00.643 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rpy-db     | 2024-03-03 03:13:00.643 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
rpy-db     | 2024-03-03 03:13:00.643 UTC [1] LOG:  listening on IPv6 address "::", port 5432
rpy-db     | 2024-03-03 03:13:00.643 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rpy-db     | 2024-03-03 03:13:00.645 UTC [67] LOG:  database system was shut down at 2024-03-03 03:13:00 UTC
rpy-db     | 2024-03-03 03:13:00.648 UTC [1] LOG:  database system is ready to accept connections
rpy-api2   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
rpy-api2   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:9998'.
rpy-api1   | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
rpy-api1   |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:9997'.
rpy-proxy  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
rpy-proxy  |       Storing keys in a directory '/home/app/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
rpy-proxy  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
rpy-proxy  |       No XML encryptor configured. Key {b883f6af-66eb-450c-8b39-761ff87b63f0} may be persisted to storage in unencrypted form.
rpy-proxy  | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
rpy-proxy  |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:9999'.
rpy-proxy  | info: Microsoft.Hosting.Lifetime[14]
rpy-proxy  |       Now listening on: http://[::]:9999
rpy-proxy  | info: Microsoft.Hosting.Lifetime[0]
rpy-proxy  |       Application started. Press Ctrl+C to shut down.
rpy-proxy  | info: Microsoft.Hosting.Lifetime[0]
rpy-proxy  |       Hosting environment: Production
rpy-proxy  | info: Microsoft.Hosting.Lifetime[0]
rpy-proxy  |       Content root path: /app
rpy-proxy  | info: Microsoft.Hosting.Lifetime[0]
rpy-proxy  |       Application is shutting down...
rpy-proxy exited with code 0
rpy-proxy exited with code 0
rpy-api2 exited with code 0
rpy-api2 exited with code 0
rpy-api1 exited with code 0
rpy-api1 exited with code 0
rpy-db     | 2024-03-03 03:17:31.822 UTC [1] LOG:  received fast shutdown request
rpy-db     | 2024-03-03 03:17:31.822 UTC [1] LOG:  aborting any active transactions
rpy-db     | 2024-03-03 03:17:31.824 UTC [1] LOG:  background worker "logical replication launcher" (PID 70) exited with exit code 1
rpy-db     | 2024-03-03 03:17:31.824 UTC [65] LOG:  shutting down
rpy-db     | 2024-03-03 03:17:31.824 UTC [65] LOG:  checkpoint starting: shutdown immediate
rpy-db     | 2024-03-03 03:17:31.827 UTC [65] LOG:  checkpoint complete: wrote 744 buffers (6.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=1930 kB, estimate=1930 kB; lsn=0/1AFE9E8, redo lsn=0/1AFE9E8
rpy-db     | 2024-03-03 03:17:31.831 UTC [1] LOG:  database system is shut down
rpy-db exited with code 0
