 Network mpsforca-vertx-kotlin_default  Creating
 Network mpsforca-vertx-kotlin_default  Created
 Container mpsforca-vertx-kotlin-db-1  Creating
 Container mpsforca-vertx-kotlin-db-1  Created
 Container mpsforca-vertx-kotlin-api01-1  Creating
 Container mpsforca-vertx-kotlin-api02-1  Creating
 Container mpsforca-vertx-kotlin-api02-1  Created
 Container mpsforca-vertx-kotlin-api01-1  Created
 Container mpsforca-vertx-kotlin-nginx-1  Creating
 Container mpsforca-vertx-kotlin-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-03-11 01:13:49.492 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-11 01:13:49.496 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-11 01:13:49.506 UTC [51] LOG:  database system was shut down at 2024-03-11 01:13:48 UTC
db-1     | 2024-03-11 01:13:49.523 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
api02-1  | HTTP server started on port 8080
api01-1  | HTTP server started on port 8080
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | DO
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-03-11 01:13:49.850 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-03-11 01:13:49.853 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-03-11 01:13:49.860 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-03-11 01:13:49.860 UTC [49] LOG:  shutting down
db-1     | 2024-03-11 01:13:49.864 UTC [49] LOG:  checkpoint starting: shutdown immediate
api01-1  | Mar 11, 2024 1:13:49 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
api01-1  | INFO: Succeeded in deploying verticle
api02-1  | Mar 11, 2024 1:13:49 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
api02-1  | INFO: Succeeded in deploying verticle
db-1     | 2024-03-11 01:13:50.352 UTC [49] LOG:  checkpoint complete: wrote 927 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.394 s, sync=0.083 s, total=0.492 s; sync files=306, longest=0.050 s, average=0.001 s; distance=4277 kB, estimate=4277 kB; lsn=0/1917F20, redo lsn=0/1917F20
db-1     | 2024-03-11 01:13:50.356 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-03-11 01:13:50.476 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-11 01:13:50.476 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-03-11 01:13:50.476 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-03-11 01:13:50.481 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-11 01:13:50.488 UTC [66] LOG:  database system was shut down at 2024-03-11 01:13:50 UTC
db-1     | 2024-03-11 01:13:50.495 UTC [1] LOG:  database system is ready to accept connections
db-1     | 2024-03-11 01:13:52.117 UTC [71] LOG:  could not receive data from client: Connection reset by peer
nginx-1  | 2024/03/11 01:13:52 [error] 29#29: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:13:53 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:13:53 [error] 29#29: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.4:8080/clientes/1/extrato", host: "localhost:9999"
db-1     | 2024-03-11 01:13:53.219 UTC [73] LOG:  could not receive data from client: Connection reset by peer
api01-1 exited with code 137
api02-1 exited with code 137
nginx-1  | 2024/03/11 01:13:55 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:13:55 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:13:57 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:13:57 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:13:59 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:13:59 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:14:01 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:14:01 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:03 [error] 29#29: *8 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:21 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:21 [error] 29#29: *8 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:26 [error] 29#29: *11 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:26 [error] 29#29: *11 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:26 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:28 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:28 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:30 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:30 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:35 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:35 [error] 29#29: *15 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:35 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:40 [error] 29#29: *17 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:40 [error] 29#29: *17 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:40 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:42 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:42 [error] 29#29: *19 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:44 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:44 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:49 [error] 29#29: *21 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:49 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:49 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:54 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:54 [error] 29#29: *23 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:15:54 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:56 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:56 [error] 29#29: *25 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:15:58 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:15:58 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:16:04 [error] 29#29: *27 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:16:04 [error] 29#29: *27 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:16:04 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:16:09 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:16:09 [error] 29#29: *29 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.29.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/11 01:16:09 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 172.29.0.1 - - [11/Mar/2024:01:16:11 +0000] "GET /clientes/1/extrato HTTP/1.1" 502 157 "-" "curl/7.81.0"
nginx-1  | 2024/03/11 01:16:11 [error] 29#29: *31 no live upstreams while connecting to upstream, client: 172.29.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-03-11 01:16:14.020 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-03-11 01:16:14.027 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-03-11 01:16:14.029 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-03-11 01:16:14.029 UTC [64] LOG:  shutting down
db-1     | 2024-03-11 01:16:14.032 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-11 01:16:14.076 UTC [64] LOG:  checkpoint complete: wrote 48 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.023 s, total=0.048 s; sync files=14, longest=0.016 s, average=0.002 s; distance=261 kB, estimate=261 kB; lsn=0/1959320, redo lsn=0/1959320
db-1     | 2024-03-11 01:16:14.079 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
