 Container api01  Creating
 Container api01  Created
 Container api02  Creating
 Container api02  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api01, api02, nginx
nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
api01  | 
api01  | 01:57:04.854 [info] Running RinhaWeb.Router with Bandit 1.2.2 at 0.0.0.0:4000 (http)
nginx  | 2024/02/24 01:57:07 [error] 30#30: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://0.0.0.0:4000/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/02/24 01:57:07 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://0.0.0.0:4001/clientes/1/extrato", host: "localhost:9999"
api01  | 
api01  | 01:57:07.449 [error] GenServer #PID<0.1576.0> terminating
api01  | ** (stop) {:aborted, {:no_exists, [:account, 1]}}
api01  |     (mnesia 4.21.4.2) mnesia.erl:362: :mnesia.abort/1
api01  |     (rinha 0.1.0) lib/rinha/accounts.ex:20: Rinha.Accounts.get_account/1
api01  |     (rinha 0.1.0) lib/rinha_web/router.ex:39: anonymous fn/2 in RinhaWeb.Router.do_match/4
api01  |     (rinha 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in RinhaWeb.Router.dispatch/2
api01  |     (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
api01  |     (rinha 0.1.0) deps/plug/lib/plug/router.ex:242: RinhaWeb.Router.dispatch/2
api01  |     (rinha 0.1.0) lib/rinha_web/router.ex:1: RinhaWeb.Router.plug_builder_call/2
api01  |     (bandit 1.2.2) lib/bandit/pipeline.ex:103: Bandit.Pipeline.call_plug/2
api01  | Last message: {:continue, :handle_connection}
api01  | 
api01  | 01:57:07.919 [info] [libcluster:gossip] connected to :api02@localhost
api01  | 
api01  | 01:57:07.920 [notice] Application mnesia exited: :stopped
api02  | 
api02  | 01:57:07.920 [notice] Application mnesia exited: :stopped
api02  | 
api02  | 01:57:07.923 [info] Running RinhaWeb.Router with Bandit 1.2.2 at 0.0.0.0:4001 (http)
api01  | 
api01  | 01:57:07.934 [info] schema has been created
api01  | 
api01  | 01:57:08.120 [info] global: Name conflict terminating {Rinha.NodeMonitor, #PID<37023.1579.0>}
api01  | 
api01  | 
api01  | 01:57:08.253 [info] accounts table has been created
api01  | 
api01  | 01:57:08.253 [info] tables have been cleared
api01  | 
api01  | 01:57:08.254 [info] Seeds successfully executed
nginx  | 2024/02/24 01:57:09 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/02/24 01:57:11 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/02/24 01:57:13 [error] 30#30: *6 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/02/24 01:57:15 [error] 30#30: *7 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/02/24 01:57:17 [error] 30#30: *8 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx exited with code 0
nginx exited with code 0
api02  | 
api02  | 02:01:31.593 [notice] SIGTERM received - shutting down
api02  | 
api02 exited with code 0
api02 exited with code 0
api01  | 
api01  | 02:01:32.867 [notice] SIGTERM received - shutting down
api01  | 
api01 exited with code 0
