 Container alcides-quarkus-db-1  Creating
 Container alcides-quarkus-db-1  Created
 Container alcides-quarkus-api02-1  Creating
 Container alcides-quarkus-api01-1  Creating
 Container alcides-quarkus-api01-1  Created
 Container alcides-quarkus-api02-1  Created
 Container alcides-quarkus-nginx-1  Creating
 Container alcides-quarkus-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-03-10 15:57:58.403 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-10 15:57:58.404 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-10 15:57:58.415 UTC [52] LOG:  database system was shut down at 2024-03-10 15:57:57 UTC
db-1     | 2024-03-10 15:57:58.417 UTC [49] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | CREATE INDEX
db-1     | CREATE FUNCTION
db-1     | CREATE FUNCTION
db-1     | INSERT 0 5
db-1     | CREATE FUNCTION
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-03-10 15:57:58.727 UTC [49] LOG:  received fast shutdown request
db-1     | .2024-03-10 15:57:58.727 UTC [49] LOG:  aborting any active transactions
db-1     | 2024-03-10 15:57:58.728 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
db-1     | 2024-03-10 15:57:58.729 UTC [50] LOG:  shutting down
db-1     | 2024-03-10 15:57:58.729 UTC [50] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-10 15:57:58.734 UTC [50] LOG:  checkpoint complete: wrote 939 buffers (45.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.001 s, total=0.006 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4303 kB, estimate=4303 kB; lsn=0/191E948, redo lsn=0/191E948
db-1     | 2024-03-10 15:57:58.737 UTC [49] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-03-10 15:57:58.838 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-10 15:57:58.838 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-03-10 15:57:58.839 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-03-10 15:57:58.839 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-10 15:57:58.840 UTC [67] LOG:  database system was shut down at 2024-03-10 15:57:58 UTC
db-1     | 2024-03-10 15:57:58.843 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/03/10 15:58:00 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 15:58:00 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:8081/clientes/1/extrato", host: "localhost:9999"
api02-1  | __  ____  __  _____   ___  __ ____  ______ 
api02-1  |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api02-1  |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api02-1  | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api02-1  | 2024-03-10 15:58:01,726 INFO  [br.com.rin.rin.ser.WarmupService] (Thread-7) Starting warmup...
api01-1  | __  ____  __  _____   ___  __ ____  ______ 
api01-1  |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
api01-1  |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
api01-1  | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
api01-1  | 2024-03-10 15:58:01,727 INFO  [br.com.rin.rin.ser.WarmupService] (Thread-7) Starting warmup...
api02-1  | 2024-03-10 15:58:01,727 ERROR [br.com.rin.rin.ser.WarmupService] (Thread-7) Error on warmup request: jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8081 [localhost/127.0.0.1] failed: Connection refused
api02-1  | 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:361)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:427)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)
api02-1  | 	at jdk.proxy4/jdk.proxy4.$Proxy47.fetchStatement(Unknown Source)
api02-1  | 	at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
api02-1  | 	at io.quarkus.restclient.runtime.QuarkusProxyInvocationHandler.invoke(QuarkusProxyInvocationHandler.java:165)
api02-1  | 	at jdk.proxy4/jdk.proxy4.$Proxy48.fetchStatement(Unknown Source)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.executeStatement(WarmupService.java:64)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.lambda$performWarmup$0(WarmupService.java:52)
api02-1  | 	at java.base@21.0.2/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
api02-1  | 	at java.base@21.0.2/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.lambda$performWarmup$1(WarmupService.java:51)
api02-1  | 	at java.base@21.0.2/java.util.stream.Streams$IntStreamBuilderImpl.forEachRemaining(Streams.java:502)
api02-1  | 	at java.base@21.0.2/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.performWarmup(WarmupService.java:51)
api02-1  | 	at java.base@21.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
api02-1  | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api02-1  | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api02-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api02-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api02-1  | Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8081 [localhost/127.0.0.1] failed: Connection refused
api02-1  | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
api02-1  | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
api02-1  | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
api02-1  | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
api02-1  | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
api02-1  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
api02-1  | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
api02-1  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
api02-1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
api02-1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:344)
api02-1  | 	... 21 more
api02-1  | Caused by: java.net.ConnectException: Connection refused
api02-1  | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api02-1  | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api02-1  | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api02-1  | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api02-1  | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api02-1  | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api02-1  | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
api02-1  | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
api02-1  | 	... 31 more
api02-1  | 
api02-1  | 2024-03-10 15:58:01,728 ERROR [br.com.rin.rin.ser.WarmupService] (Thread-7) Error on warmup request: jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8081 [localhost/127.0.0.1] failed: Connection refused
api02-1  | 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:361)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:427)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)
api02-1  | 	at jdk.proxy4/jdk.proxy4.$Proxy47.registerTransaction(Unknown Source)
api02-1  | 	at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
api02-1  | 	at io.quarkus.restclient.runtime.QuarkusProxyInvocationHandler.invoke(QuarkusProxyInvocationHandler.java:165)
api02-1  | 	at jdk.proxy4/jdk.proxy4.$Proxy48.registerTransaction(Unknown Source)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.executeTransaction(WarmupService.java:72)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.lambda$performWarmup$0(WarmupService.java:53)
api02-1  | 	at java.base@21.0.2/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
api02-1  | 	at java.base@21.0.2/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.lambda$performWarmup$1(WarmupService.java:51)
api02-1  | 	at java.base@21.0.2/java.util.stream.Streams$IntStreamBuilderImpl.forEachRemaining(Streams.java:502)
api02-1  | 	at java.base@21.0.2/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
api02-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.performWarmup(WarmupService.java:51)
api02-1  | 	at java.base@21.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
api02-1  | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api02-1  | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api02-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api02-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api02-1  | Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8081 [localhost/127.0.0.1] failed: Connection refused
api02-1  | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
api02-1  | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
api02-1  | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
api02-1  | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
api02-1  | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
api02-1  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
api02-1  | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
api02-1  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
api02-1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
api02-1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
api02-1  | 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:344)
api02-1  | 	... 21 more
api02-1  | Caused by: java.net.ConnectException: Connection refused
api02-1  | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api02-1  | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api02-1  | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api02-1  | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api02-1  | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api02-1  | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api02-1  | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
api02-1  | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
api02-1  | 	... 31 more
api02-1  | 
api02-1  | 2024-03-10 15:58:01,728 INFO  [io.quarkus] (main) rinha-app 1.0.0-SNAPSHOT native (powered by Quarkus 3.7.4) started in 5.065s. Listening on: http://0.0.0.0:8081
api02-1  | 2024-03-10 15:58:01,728 INFO  [io.quarkus] (main) Profile prod activated. 
api02-1  | 2024-03-10 15:58:01,728 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, jdbc-postgresql, narayana-jta, resteasy-client, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
api01-1  | 2024-03-10 15:58:01,729 ERROR [br.com.rin.rin.ser.WarmupService] (Thread-7) Error on warmup request: jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused
api01-1  | 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:361)
api01-1  | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:427)
api01-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
api01-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
api01-1  | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)
api01-1  | 	at jdk.proxy4/jdk.proxy4.$Proxy47.fetchStatement(Unknown Source)
api01-1  | 	at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
api01-1  | 	at io.quarkus.restclient.runtime.QuarkusProxyInvocationHandler.invoke(QuarkusProxyInvocationHandler.java:165)
api01-1  | 	at jdk.proxy4/jdk.proxy4.$Proxy48.fetchStatement(Unknown Source)
api01-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.executeStatement(WarmupService.java:64)
api01-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.lambda$performWarmup$0(WarmupService.java:52)
api01-1  | 	at java.base@21.0.2/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
api01-1  | 	at java.base@21.0.2/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
api01-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.lambda$performWarmup$1(WarmupService.java:51)
api01-1  | 	at java.base@21.0.2/java.util.stream.Streams$IntStreamBuilderImpl.forEachRemaining(Streams.java:502)
api01-1  | 	at java.base@21.0.2/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
api01-1  | 	at br.com.rinha.rinhabackend.service.WarmupService.performWarmup(WarmupService.java:51)
api01-1  | 	at java.base@21.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
api01-1  | 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
api01-1  | 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
api01-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
api01-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
api01-1  | Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused
api01-1  | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
api01-1  | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
api01-1  | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
api01-1  | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
api01-1  | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
api01-1  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
api01-1  | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
api01-1  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
api01-1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
api01-1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
api01-1  | 	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:344)
api01-1  | 	... 21 more
api01-1  | Caused by: java.net.ConnectException: Connection refused
api01-1  | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnect(Native Method)
api01-1  | 	at java.base@21.0.2/sun.nio.ch.Net.pollConnectNow(Net.java:682)
api01-1  | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
api01-1  | 	at java.base@21.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
api01-1  | 	at java.base@21.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
api01-1  | 	at java.base@21.0.2/java.net.Socket.connect(Socket.java:751)
api01-1  | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
api01-1  | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
api01-1  | 	... 31 more
api01-1  | 
api01-1  | 2024-03-10 15:58:01,729 INFO  [io.quarkus] (main) rinha-app 1.0.0-SNAPSHOT native (powered by Quarkus 3.7.4) started in 5.066s. Listening on: http://0.0.0.0:8080
api01-1  | 2024-03-10 15:58:01,729 INFO  [io.quarkus] (main) Profile prod activated. 
api01-1  | 2024-03-10 15:58:01,729 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, jdbc-postgresql, narayana-jta, resteasy-client, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
api02-1  | 2024-03-10 15:58:01,775 INFO  [br.com.rin.rin.ser.WarmupService] (Thread-7) finished warmup
api01-1  | 2024-03-10 15:58:01,776 INFO  [br.com.rin.rin.ser.WarmupService] (Thread-7) finished warmup
nginx-1  | 2024/03/10 15:58:02 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 15:58:04 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 15:58:06 [error] 30#30: *6 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 15:58:08 [error] 30#30: *7 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 15:58:10 [error] 30#30: *8 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api01-1  | 2024-03-10 16:02:25,232 INFO  [io.quarkus] (Shutdown thread) rinha-app stopped in 0.006s
api02-1  | 2024-03-10 16:02:25,239 INFO  [io.quarkus] (main) rinha-app stopped in 0.006s
api01-1 exited with code 0
api01-1 exited with code 143
api02-1 exited with code 0
api02-1 exited with code 143
db-1     | 2024-03-10 16:02:25.679 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-03-10 16:02:25.679 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-03-10 16:02:25.681 UTC [1] LOG:  background worker "logical replication launcher" (PID 70) exited with exit code 1
db-1     | 2024-03-10 16:02:25.681 UTC [65] LOG:  shutting down
db-1     | 2024-03-10 16:02:25.681 UTC [65] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-10 16:02:25.685 UTC [65] LOG:  checkpoint complete: wrote 979 buffers (47.8%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.004 s, sync=0.001 s, total=0.005 s; sync files=0, longest=0.000 s, average=0.000 s; distance=22649 kB, estimate=22649 kB; lsn=0/2F3CF08, redo lsn=0/2F3CF08
db-1     | 2024-03-10 16:02:25.688 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
